name: Github Pages Pusher

on:
  pull_request:
    branches: [ master ]
    types: [ synchronize, opened ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v2
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
=======
      - uses: actions/checkout@v2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
>>>>>>> 481dfbbaf1e3a7742539a1b8b0d4fb2e8ca85486
